# Generated by Django 6.0.4 on 2026-04-19 11:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("DSA", "Data Structures & Algorithms"),
                            ("DS", "Data Science"),
                            ("ROB", "Robotics"),
                            ("EC", "Electronics & Communication"),
                        ],
                        help_text="The study domain this category represents.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for UI and chart rendering (e.g. #4F46E5).",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start_date",
                    models.DateField(
                        help_text="The Monday of the week this goal is for."
                    ),
                ),
                (
                    "target_description",
                    models.TextField(
                        help_text="What exactly do you plan to study or accomplish this week?"
                    ),
                ),
                (
                    "target_hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Total hours targeted for this goal this week (e.g. 10.5).",
                        max_digits=4,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Mark True when the weekly goal has been fully achieved.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="The study domain this goal belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_goals",
                        to="tracker.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Goal",
                "ordering": ["-week_start_date", "category"],
                "unique_together": {("category", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="The date of this log entry.",
                    ),
                ),
                (
                    "hours_spent",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Hours actually spent on this goal today (e.g. 2.5).",
                        max_digits=4,
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True,
                        help_text="What did you accomplish? Key concepts covered, problems solved, etc.",
                    ),
                ),
                (
                    "blockers",
                    models.TextField(
                        blank=True,
                        help_text="What slowed you down? Confusion, distractions, missing resources?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weekly_goal",
                    models.ForeignKey(
                        help_text="The weekly goal this log entry contributes toward.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="tracker.weeklygoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Log",
                "ordering": ["-date"],
                "unique_together": {("weekly_goal", "date")},
            },
        ),
    ]
